#表示验证登录信息的库
spring:
  data:
    mongodb:
      authentication-database: admin
      #配置表示要连接的库，认证信息不一定要在连接的库中创建
      database: admin
      #数据库连接地址
      host: 127.0.0.1
      #数据库端口
      port: 27017
      #数据库认证信息
      username: zfliu
      password: '123456'
